name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: pytest (${{ matrix.os }} / py${{ matrix.py }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,]
        py: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package (dev extras)
        run: pip install -e .[dev]

      - name: Run pytest
        run: pytest -v
